### ISSUE TITLE
Local Sensitive Data Analysis

### ISSUE THREAD

**Issue by jmanico** [6mile/DevSecOps-Playbook#4]
"Local Sensitive Data Analysis" is just a typical and rather old school feature that we see in SAST and other scanning tools, why do you split it out as a separate tool-type?

For example:

https://semgrep.dev/p/secrets

**Comment by 6mile** [comment]
I think it's super important to split it out, and hence why I did it.  Just because semgrep and some other tools include it as a module doesn't mean that a) people understand what it is and b) are actually doing it.  And at the end of the day, that's what the DevSecOps Playbook is all about:  Helping orgs understand that its important to do to accelerate their DevSecOps journey.
